### ISSUE TITLE
合作问题

### ISSUE THREAD

**Issue by dsherb628** [zhoukekestar/chrome-extension-amazon-autobuy#1]
您的Amazon自动刷单插件非常棒。

目前我们的业务也涉及到这方面的需求，正想自己弄一个类似的插件（功能略有差异），然后机缘巧合下看到了这个插件。

因此，联系到您这边，希望大家可以谈一下合作。您做过这个插件，对其中的原理非常了解，比我们自己做起来会要快很多。具体的费用要求，可以详谈。

如有意，烦请邮件联系dsherb628@qq.com.

**Comment by zhoukekestar** [comment]
[Demo视频](http://pan.baidu.com/s/1o8Ncz7k)
写玩代码，然后@dsherb628 没音讯。。。
